# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
    - name: Welcome New Users
      # You may pin to the exact commit or the version.
      # uses: bubkoo/welcome-action@b2a210e588422e94634bd8666708229d79c3070a
      uses: bubkoo/welcome-action@v1.0.1
      with:
        # Your GitHub token for authentication.
        GITHUB_TOKEN: 
        # Comment to be posted to on first time issues.
        FIRST_ISSUE: # optional
        # Comment to be posted to on first time issues.
        FIRST_ISSUE_COMMENT: # optional
        # Reactions to be add to comment on first time issues.
        FIRST_ISSUE_REACTIONS: # optional
        # Comment to be posted to on PRs from first time contributors in your repository.
        FIRST_PR: # optional
        # Comment to be posted to on PRs from first time contributors in your repository.
        FIRST_PR_COMMENT: # optional
        # Reactions to be add to comment on PRs from first time contributors in your repository.
        FIRST_PR_REACTIONS: # optional
        # Comment to be posted to on pull requests merged by a first time user.
        FIRST_PR_MERGED: # optional
        # Comment to be posted to on pull requests merged by a first time user.
        FIRST_PR_MERGED_COMMENT: # optional
        # Reactions to be add to comment on pull requests merged by a first time user.
        FIRST_PR_MERGED_REACTIONS: # optional          


